### PR TITLE
Add types as dependencies.

### PR DESCRIPTION
**Pull request by ksaaskil**
- ~~Fixes the issue where `RequestResponseSpy` is typed as `any` because types from `sinon` are not included in the npm package~~ *EDIT: sinon types were added as dependencies in #203 so this can be a separate PR*
- See the discussion in #186

### CODE REVIEW

**Comment by ksaaskil** [comment]
But if they're in the lerna level, then individual packages do not include their own type dependencies I assume? Or they include the type dependencies of all packages? Neither of those sounds right to me 🤔

**Comment by idantene** [comment]
Fair points. Maybe it's just the dev dependencies then.

**Comment by ksaaskil** [comment]
Waiting for the final approval and fixing looots of conflicts, probably easier to just start over as so many dependencies have come and gone... Why so, is this causing trouble?

**Comment by ksaaskil** [comment]
So much has changed since this was implemented that it's easier to just start over.

**Pull request closed without merging**
