### PR TITLE
Read env variables from context in the publish step.

### PR DESCRIPTION
**Pull request by ksaaskil**
- [x]  Add required tokens to the context.
- [ ]  Delete tokens from the job's environment variables

### CODE REVIEW

**Comment by idantene** [comment]
I think, if we're using a Git token, then we can also remove the credentials helper bash script (and corresponding username/password environment variables).

**Comment by ksaaskil** [comment]
You mean setting `git config user.password $GIT_TOKEN`? This only changes how CircleCI injects $GIT_TOKEN so I'm not sure I understand what you mean by "I think, if we're using a Git token, ..."

**Comment by idantene** [comment]
Yup, or as needed. Just saying I think we can remove the bash script altogether at this point IMO.

**Comment by ksaaskil** [comment]
I kinda think using `git config credential.helper ...` is better, using `git config user.password $GIT_TOKEN` seems more suspectible to leaking the token if someone, for example, wanted to debug the script and set `set -x` in CircleCI 🤔

**Pull request merged**
